-- Harden the synchronized Fit App state without deleting or rewriting existing
-- user payloads. Every successful change gets an immutable server revision and
-- clients save through an atomic compare-and-swap RPC to prevent lost updates.

alter table public.lockin_state_user
  add column if not exists state_version bigint;

update public.lockin_state_user
set state_version = 1
where state_version is null;

alter table public.lockin_state_user
  alter column state_version set default 1,
  alter column state_version set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'lockin_state_user_state_version_positive'
      and conrelid = 'public.lockin_state_user'::regclass
  ) then
    alter table public.lockin_state_user
      add constraint lockin_state_user_state_version_positive
      check (state_version > 0);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'lockin_state_user_payload_object'
      and conrelid = 'public.lockin_state_user'::regclass
  ) then
    alter table public.lockin_state_user
      add constraint lockin_state_user_payload_object
      check (jsonb_typeof(payload) = 'object');
  end if;
end
$$;

create table if not exists public.lockin_state_revisions (
  revision_id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  state_version bigint not null check (state_version > 0),
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  device_id text,
  reason text not null default 'sync' check (reason in ('migration', 'initial', 'sync', 'restore')),
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, state_version)
);

create index if not exists lockin_state_revisions_user_created_idx
  on public.lockin_state_revisions (user_id, created_at desc);

alter table public.lockin_state_revisions enable row level security;

revoke all on table public.lockin_state_revisions from anon;
revoke all on table public.lockin_state_revisions from authenticated;
grant select on table public.lockin_state_revisions to authenticated;
grant all on table public.lockin_state_revisions to service_role;

drop policy if exists lockin_revision_select on public.lockin_state_revisions;

create policy lockin_revision_select
on public.lockin_state_revisions
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

-- Preserve the current state as version 1 when upgrading an existing account.
insert into public.lockin_state_revisions (
  user_id,
  state_version,
  payload,
  device_id,
  reason,
  created_at
)
select
  user_id,
  state_version,
  payload,
  'migration',
  'migration',
  updated_at
from public.lockin_state_user
on conflict (user_id, state_version) do nothing;

create or replace function public.save_lockin_state(
  p_payload jsonb,
  p_expected_version bigint default 0,
  p_device_id text default null,
  p_force boolean default false
)
returns table (
  saved boolean,
  conflict boolean,
  state_version bigint,
  state_updated_at timestamptz,
  state_payload jsonb
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_current public.lockin_state_user%rowtype;
  v_inserted integer := 0;
  v_new_version bigint;
  v_updated_at timestamptz := clock_timestamp();
  v_device_id text := left(nullif(trim(p_device_id), ''), 120);
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'State payload must be a JSON object' using errcode = '22023';
  end if;

  if octet_length(p_payload::text) > 5000000 then
    raise exception 'State payload exceeds the 5 MB safety limit' using errcode = '22001';
  end if;

  -- The insert is safe even if two new devices try to create the account row
  -- at the same time. Only one wins; the other continues through CAS below.
  if p_force or coalesce(p_expected_version, 0) = 0 then
    insert into public.lockin_state_user (
      user_id,
      payload,
      state_version,
      updated_at,
      created_at
    )
    values (
      v_user_id,
      p_payload,
      1,
      v_updated_at,
      v_updated_at
    )
    on conflict (user_id) do nothing;

    get diagnostics v_inserted = row_count;

    if v_inserted = 1 then
      insert into public.lockin_state_revisions (
        user_id,
        state_version,
        payload,
        device_id,
        reason,
        created_at
      )
      values (
        v_user_id,
        1,
        p_payload,
        v_device_id,
        'initial',
        v_updated_at
      );

      return query
      select true, false, 1::bigint, v_updated_at, p_payload;
      return;
    end if;
  end if;

  select current_state.*
  into v_current
  from public.lockin_state_user as current_state
  where current_state.user_id = v_user_id
  for update;

  if not found then
    return query
    select false, true, 0::bigint, null::timestamptz, null::jsonb;
    return;
  end if;

  if not p_force and coalesce(p_expected_version, 0) <> v_current.state_version then
    return query
    select false, true, v_current.state_version, v_current.updated_at, v_current.payload;
    return;
  end if;

  -- A retry of an already committed payload is idempotent and does not create
  -- duplicate versions.
  if v_current.payload = p_payload then
    return query
    select true, false, v_current.state_version, v_current.updated_at, v_current.payload;
    return;
  end if;

  v_new_version := v_current.state_version + 1;

  update public.lockin_state_user as current_state
  set
    payload = p_payload,
    state_version = v_new_version,
    updated_at = v_updated_at
  where current_state.user_id = v_user_id;

  insert into public.lockin_state_revisions (
    user_id,
    state_version,
    payload,
    device_id,
    reason,
    created_at
  )
  values (
    v_user_id,
    v_new_version,
    p_payload,
    v_device_id,
    'sync',
    v_updated_at
  );

  return query
  select true, false, v_new_version, v_updated_at, p_payload;
end
$$;

create or replace function public.restore_lockin_state(
  p_revision_id bigint,
  p_expected_version bigint
)
returns table (
  saved boolean,
  conflict boolean,
  state_version bigint,
  state_updated_at timestamptz,
  state_payload jsonb
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_revision_payload jsonb;
  v_current public.lockin_state_user%rowtype;
  v_new_version bigint;
  v_updated_at timestamptz := clock_timestamp();
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select revision.payload
  into v_revision_payload
  from public.lockin_state_revisions as revision
  where revision.revision_id = p_revision_id
    and revision.user_id = v_user_id;

  if not found then
    raise exception 'Revision not found' using errcode = 'P0002';
  end if;

  select current_state.*
  into v_current
  from public.lockin_state_user as current_state
  where current_state.user_id = v_user_id
  for update;

  if not found then
    return query
    select false, true, 0::bigint, null::timestamptz, null::jsonb;
    return;
  end if;

  if coalesce(p_expected_version, 0) <> v_current.state_version then
    return query
    select false, true, v_current.state_version, v_current.updated_at, v_current.payload;
    return;
  end if;

  if v_current.payload = v_revision_payload then
    return query
    select true, false, v_current.state_version, v_current.updated_at, v_current.payload;
    return;
  end if;

  v_new_version := v_current.state_version + 1;

  update public.lockin_state_user as current_state
  set
    payload = v_revision_payload,
    state_version = v_new_version,
    updated_at = v_updated_at
  where current_state.user_id = v_user_id;

  insert into public.lockin_state_revisions (
    user_id,
    state_version,
    payload,
    device_id,
    reason,
    created_at
  )
  values (
    v_user_id,
    v_new_version,
    v_revision_payload,
    'server-restore',
    'restore',
    v_updated_at
  );

  return query
  select true, false, v_new_version, v_updated_at, v_revision_payload;
end
$$;

-- Signed-in clients can read only their current row. Writes are forced through
-- the two RPCs above so version checks and immutable revisions cannot be
-- bypassed by the frontend.
revoke all on table public.lockin_state_user from anon;
revoke all on table public.lockin_state_user from authenticated;
grant select on table public.lockin_state_user to authenticated;
grant all on table public.lockin_state_user to service_role;

drop policy if exists lockin_user_select on public.lockin_state_user;
drop policy if exists lockin_user_insert on public.lockin_state_user;
drop policy if exists lockin_user_update on public.lockin_state_user;

create policy lockin_user_select
on public.lockin_state_user
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

revoke all on function public.save_lockin_state(jsonb, bigint, text, boolean) from public;
revoke all on function public.save_lockin_state(jsonb, bigint, text, boolean) from anon;
grant execute on function public.save_lockin_state(jsonb, bigint, text, boolean) to authenticated;
grant execute on function public.save_lockin_state(jsonb, bigint, text, boolean) to service_role;

revoke all on function public.restore_lockin_state(bigint, bigint) from public;
revoke all on function public.restore_lockin_state(bigint, bigint) from anon;
grant execute on function public.restore_lockin_state(bigint, bigint) to authenticated;
grant execute on function public.restore_lockin_state(bigint, bigint) to service_role;

comment on column public.lockin_state_user.state_version is
  'Monotonic compare-and-swap version used to prevent multi-device lost updates.';

comment on table public.lockin_state_revisions is
  'Immutable per-account Fit App state history used for recovery.';

comment on function public.save_lockin_state(jsonb, bigint, text, boolean) is
  'Atomically saves the authenticated user state when the expected version matches.';

comment on function public.restore_lockin_state(bigint, bigint) is
  'Restores one authenticated user revision as a new immutable state version.';
